import ui

GLOBAL_HTML_ATTR = {
                    "accesskey":ui.TextField(),
                    "class":ui.TextField(),
                    "cententeditable":ui.TextField(),
                    "contextmenu":ui.TextField(),
                    "dir":ui.TextField(),
                    "draggable":ui.TextField(),
                    "dropzone":ui.TextField(),
                    "hidden":ui.TextField(),
                    "id":ui.TextField(),
                    "lang":ui.TextField(),
                    "spellcheck":ui.TextField(),
                    "style":ui.TextField(),
                    "tabindex":ui.TextField(),
                    "title":ui.TextField(),
                    "translate":ui.TextField(),
                    "name":ui.TextField(),
                    }

WINDOW_EVENTS = {
                 "onafterprint":ui.TextField(),
                 "onbeforeprint":ui.TextField(),
                 "onbeforeunload":ui.TextField(),
                 "onerror":ui.TextField(),
                 "onhashchange":ui.TextField(),
                 "onload":ui.TextField(),
                 "onmessage":ui.TextField(),
                 "onoffline":ui.TextField(),
                 "ononline":ui.TextField(),
                 "onpagehide":ui.TextField(),
                 "onpageshow":ui.TextField(),
                 "onpopstate":ui.TextField(),
                 "onresize":ui.TextField(),
                 "onstorage":ui.TextField(),
                 "onunload":ui.TextField(),
                 }
                 
FORM_EVENTS = {
               "onblur":ui.TextField(),
               "onchange":ui.TextField(),
               "oncontextmenu":ui.TextField(),
               "onfocus":ui.TextField(),
               "oninput":ui.TextField(),
               "oninvalid":ui.TextField(),
               "onreset":ui.TextField(),
               "onsearch":ui.TextField(),
               "onselect":ui.TextField(),
               "onsubmit":ui.TextField(),
               }
               
KEYBOARD_EVENTS = {
                   "onkeydown":ui.TextField(),
                   "onkeypress":ui.TextField(),
                   "onkeyup":ui.TextField(),
                   }
                   
MOUSE_EVENTS = {
                "onclick":ui.TextField(),
                "ondblclick":ui.TextField(),
                "ondrag":ui.TextField(),
                "ondragend":ui.TextField(),
                "ondragenter":ui.TextField(),
                "ondragleave":ui.TextField(),
                "ondragover":ui.TextField(),
                "ondragstart":ui.TextField(),
                "ondrop":ui.TextField(),
                "onmousedown":ui.TextField(),
                "onmousemove":ui.TextField(),
                "onmouseout":ui.TextField(),
                "onmouseover":ui.TextField(),
                "onmouseup":ui.TextField(),
                "onmousewheel":ui.TextField(),
                "onscroll":ui.TextField(),
                "onwheel":ui.TextField(),
                }
                
CLIPBOARD_EVENTS = {
                    "oncopy":ui.TextField(),
                    "oncut":ui.TextField(),
                    "onpaste":ui.TextField(),
                    }

MEDIA_EVENTS = {
                "onabord":ui.TextField(),
                "oncanplay":ui.TextField(),
                "oncanplaythrough":ui.TextField(),
                "oncuechange":ui.TextField(),
                "onduraionchange":ui.TextField(),
                "onemptied":ui.TextField(),
                "onended":ui.TextField(),
                "onerror":ui.TextField(),
                "onloadeddata":ui.TextField(),
                "onloadedmetadata":ui.TextField(),
                "onloadstart":ui.TextField(),
                "onpause":ui.TextField(),
                "onplay":ui.TextField(),
                "onplaying":ui.TextField(),
                "onprogress":ui.TextField(),
                "onratechange":ui.TextField(),
                "onseeked":ui.TextField(),
                "onseeking":ui.TextField(),
                "onstalled":ui.TextField(),
                "onsuspend":ui.TextField(),
                "ontimeupdate":ui.TextField(),
                "onvolumechange":ui.TextField(),
                "onwaiting":ui.TextField(),
                }

MISC_EVENTS = {
               "onerror":ui.TextField(),
               "onshow":ui.TextField(),
               "ontoggle":ui.TextField(),
               }
               
ALL_EVENTS = dict(WINDOW_EVENTS,
                  **dict(FORM_EVENTS,
                         **dict(KEYBOARD_EVENTS,
                                **dict(MOUSE_EVENTS,
                                       **dict(CLIPBOARD_EVENTS,
                                              **dict(MEDIA_EVENTS,
                                                     **MISC_EVENTS))))))

TAGS = [
        {"title": "anchor",
         "options": dict({
                     "tag-open":"a",
                     "tag-close":"a",
                     "content":ui.TextField(),
                     "charset":ui.TextField(),
                     "coords":ui.TextField(),
                     "download":ui.TextField(),
                     "href":ui.TextField(),
                     "hreflang":ui.TextField(),
                     "media":ui.TextField(),
                     "rel":ui.TextField(),
                     "rev":ui.TextField(),
                     "shape":ui.TextField(),
                     "target":ui.TextField(),
                     "type":ui.TextField(),
                     }, **GLOBAL_HTML_ATTR)},
        {"title":"abbreviation",
         "options": dict({
                          "tag-open":"abbr",
                          "tag-close":"abbr",
                          "content":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"acronym - (Not Avaliable in HTML5)",
         "options": dict({
                          "tag-open":"acronym",
                          "tag-close":"acronym",
                          "contents":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"address",
         "options": dict({
                          "tag-open":"address",
                          "tag-close":"address",
                          "content":ui.TextView(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"applet - (Not Avaliable in HTML5)",
         "options": dict({
                          "tag-open":"applet",
                          "tag-close":"applet",
                          "content":"",
                          "code":ui.TextField(),
                          "object":ui.TextField(),
                          "align":ui.TextField(),
                          "alt":ui.TextField(),
                          "archive":ui.TextField(),
                          "codebase":ui.TextField(),
                          "height":ui.TextField(),
                          "hspace":ui.TextField(),
                          "vspace":ui.TextField(),
                          "width":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"area",
         "options": dict({
                          "tag-open":"area",
                          "tag-close":"area",
                          "alt":ui.TextField(),
                          "coords":ui.TextField(),
                          "download":ui.TextField(),
                          "href":ui.TextField(),
                          "hreflang":ui.TextField(),
                          "media":ui.TextField(),
                          "nohref":ui.TextField(),
                          "rel":ui.TextField(),
                          "shape":ui.TextField(),
                          "target":ui.TextField(),
                          "type":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"article",
         "options": dict({
                          "tag-open":"article",
                          "tag-close":"article",
                          "content":ui.TextView(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"aside",
         "options": dict({
                          "tag-open":"aside",
                          "tag-close":"aside",
                          "content":ui.TextView()
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"audio",
         "options": dict({
                          "tag-open":"audio",
                          "tag-close":"audio",
                          "content":ui.TextField(),
                          "preload":ui.TextField(),
                          "src":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"bold",
         "options": dict({
                          "tag-open":"b",
                          "tag-close":"b",
                          "content":ui.TextView(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"base",
         "options": dict({
                          "tag-open":"base",
                          "tag-close":"base",
                          "href":ui.TextField(),
                          "target":ui.TextField(),
                          "content":"",
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"basefont - (Not Avaliable in HTML5)",
         "options": dict({
                          "tag-open":"basefont",
                          "tag-close":"basefont",
                          "content":"",
                          "color":ui.TextField(),
                          "face":ui.TextField(),
                          "size":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"Bi-directional Isolation",
         "options": dict({
                          "tag-open":"bdi",
                          "tag-close":"bdi",
                          "content":ui.TextView(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"Bi-directional Override",
         "options": dict({
                          "tag-open":"bdo",
                          "tag-close":"bdo",
                          "content":ui.TextView(),
                          "dir":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"big - (Not Avaliable in HTML5)",
         "options": dict({
                          "tag-open":"big",
                          "tag-close":"big",
                          "content":ui.TextView(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"blockquote",
         "options": dict({
                          "tag-open":"blockquote",
                          "tag-close":"blockquote",
                          "content":ui.TextView(),
                          "cite":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"body",
         "options": dict({
                          "tag-open":"body",
                          "tag-close":"body",
                          "content":ui.TextView(),
                          "alink":ui.TextField(),
                          "background":ui.TextField(),
                          "bgcolor":ui.TextField(),
                          "link":ui.TextField(),
                          "text":ui.TextField(),
                          "vlink":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"line break",
         "options": dict({
                          "tag-open":"br",
                          "tag-close":"br",
                          "content":ui.TextView(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"button",
         "options": dict({
                          "tag-open":"button",
                          "tag-close":"button",
                          "content":ui.TextField(),
                          "autofocus":ui.TextField(),
                          "disabled":ui.TextField(),
                          "form":ui.TextField(),
                          "formaction":ui.TextField(),
                          "formenctype":ui.TextField(),
                          "formmethod":ui.TextField(),
                          "formnovalidate":ui.TextField(),
                          "formtarget":ui.TextField(),
                          "name":ui.TextField(),
                          "type":ui.TextField(),
                          "value":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"canvas",
         "options": dict({
                          "tag-open":"canvas",
                          "tag-close":"canvas",
                          "content":ui.TextField(),
                          "height":ui.TextField(),
                          "width":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"caption",
         "options": dict({
                          "tag-open":"caption",
                          "tag-close":"caption",
                          "content":ui.TextView(),
                          "align":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"center",
         "options": dict({
                          "tag-open":"center",
                          "tag-close":"center",
                          "content":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"cite",
         "options": dict({
                          "tag-open":"cite",
                          "tag-close":"cite",
                          "content":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"code - (CSS Provides Richer Effects)",
         "options": dict({
                          "tag-open":"code",
                          "tag-close":"code",
                          "content":ui.TextView(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"col",
         "options": dict({
                          "tag-open":"col",
                          "align":ui.TextField(),
                          "char":ui.TextField(),
                          "charoff":ui.TextField(),
                          "span":ui.TextField(),
                          "valign":ui.TextField(),
                          "width":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"colgroup",
         "options": dict({
                          "tag-open":"colgroup",
                          "tag-close":"colgroup",
                          "content":ui.TextField(),
                          "align":ui.TextField(),
                          "char":ui.TextField(),
                          "charoff":ui.TextField(),
                          "span":ui.TextField(),
                          "valign":ui.TextField(),
                          "width":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"datalist",
         "options": dict({
                          "tag-open":"datalist",
                          "tag-close":"datalist",
                          "content":ui.TextView(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"Description (dd)",
         "options": dict({
                          "tag-open":"dd",
                          "tag-close":"dd",
                          "content":ui.TextView(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"delete (del)",
         "options": dict({
                          "tag-open":"del",
                          "tag-close":"del",
                          "content":ui.TextView(),
                          "cite":ui.TextField(),
                          "datetime":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"details",
         "options": dict({
                          "tag-open":"details",
                          "tag-close":"details",
                          "content":ui.TextView(),
                          "open":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"definition (dfn)",
         "options": dict({
                          "tag-open":"dfn",
                          "tag-close":"dfn",
                          "content":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"dialog",
         "options": dict({
                          "tag-open":"dialog",
                          "tag-close":"dialog",
                          "content":ui.TextView(),
                          "open":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"dir - (Not Avaliable in HTML5)",
         "options": dict({
                          "tag-open":"dir",
                          "tag-close":"dir",
                          "content":ui.TextField(),
                          "compact":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"div",
         "options": dict({
                          "tag-open":"div",
                          "tag-close":"div",
                          "content":ui.TextView(),
                          "align":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"description list (dl)",
         "options": dict({
                          "tag-open":"dl",
                          "tag-close":"dl",
                          "content":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"description term (dt)",
         "options": dict({
                          "tag-open":"dt",
                          "tag-close":"dt",
                          "content":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"emphasis - em (Richer effects attained with CSS)",
         "options": dict({
                          "tag-open":"em",
                          "tag-close":"em",
                          "content":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"embed",
         "options": dict({
                          "tag-open":"embed",
                          "tag-close":"embed",
                          "content":ui.TextField(),
                          "height":ui.TextField(),
                          "src":ui.TextField(),
                          "type":ui.TextField(),
                          "width":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"fieldset",
         "options": dict({
                          "tag-open":"fieldset",
                          "tag-close":"fieldset",
                          "content":ui.TextView(),
                          "disabled":ui.TextField(),
                          "form_id":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"figcaption",
         "options": dict({
                          "tag-open":"figcaption",
                          "tag-close":"figcaption",
                          "content":ui.TextField(),
        
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"figure",
         "options": dict({
                          "tag-open":"figure",
                          "tag-close":"figure",
                          "content":ui.TextField(),
        
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"font - (Not Avaliable in HTML5)",
         "options": dict({
                          "tag-open":"font",
                          "tag-close":"font",
                          "content":ui.TextField(),
                          "color":ui.TextField(),
                          "face":ui.TextField(),
                          "size":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"footer",
         "options": dict({
                          "tag-open":"footer",
                          "tag-close":"footer",
                          "content":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"form",
         "options": dict({
                          "tag-open":"form",
                          "tag-close":"form",
                          "content":ui.TextView(),
                          "accept":ui.TextField(),
                          "accept-charset":ui.TextField(),
                          "action":ui.TextField(),
                          "autocomplete":ui.TextField(),
                          "enctype":ui.TextField(),
                          "method":ui.TextField(),
                          "novalidate":ui.TextField(),
                          "target":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"frame - (Not Avaliable in HTML5)",
         "options": dict({
                          "tag-open":"frame",
                          "tag-close":"frame",
                          "content":ui.TextField(),
                          "frameborder":ui.TextField(),
                          "longdesc":ui.TextField(),
                          "marginheight":ui.TextField(),
                          "marginwidth":ui.TextField(),
                          "noresize":ui.TextField(),
                          "scrolling":ui.TextField(),
                          "src":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"frameset - (Not Avaliable in HTML5)",
         "options": dict({
                          "tag-open":"frameset",
                          "tag-close":"frameset",
                          "content":ui.TextField(),
                          "cols":ui.TextField(),
                          "rows":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"heading 1",
         "options": dict({
                          "tag-open":"h1",
                          "tag-close":"h1",
                          "conent":ui.TextField(),
                          "align":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"heading 2",
         "options": dict({
                          "tag-open":"h2",
                          "tag-close":"h2",
                          "conent":ui.TextField(),
                          "align":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"heading 3",
         "options": dict({
                          "tag-open":"h3",
                          "tag-close":"h3",
                          "conent":ui.TextField(),
                          "align":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"heading 4",
         "options": dict({
                          "tag-open":"h4",
                          "tag-close":"h4",
                          "conent":ui.TextField(),
                          "align":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"heading 5",
         "options": dict({
                          "tag-open":"h5",
                          "tag-close":"h5",
                          "conent":ui.TextField(),
                          "align":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"heading 6",
         "options": dict({
                          "tag-open":"h6",
                          "tag-close":"h6",
                          "conent":ui.TextField(),
                          "align":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"head",
         "options": dict({
                          "tag-open":"head",
                          "tag-close":"head",
                          "content":ui.TextField(),
                          "profile":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"header",
         "options": dict({
                          "tag-open":"header",
                          "tag-close":"header",
                          "content":ui.TextView(),
        
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"hr",
         "options": dict({
                          "tag-open":"hr",
                          "align":ui.TextField(),
                          "noshade":ui.TextField(),
                          "size":ui.TextField(),
                          "width":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"html",
         "options": dict({
                          "tag-open":"html",
                          "tag-close":"html",
                          "content":ui.TextField(),
                          "manifest":ui.TextField(),
                          "xmlns":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"i",
         "options": dict({
                          "tag-open":"i",
                          "tag-close":"i",
                          "content":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"iframe",
         "options": dict({
                          "tag-open":"iframe",
                          "tag-close":"iframe",
                          "content":ui.TextField(),
                          "align":ui.TextField(),
                          "frameborder":ui.TextView(),
                          "height":ui.TextField(),
                          "longdesc":ui.TextField(),
                          "marginheight":ui.TextField(),
                          "marginwidth":ui.TextField(),
                          "sandbox":ui.TextField(),
                          "scrolling":ui.TextField(),
                          "seamless":ui.TextField(),
                          "src":ui.TextField(),
                          "srcdoc":ui.TextField(),
                          "width":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"image",
         "options": dict({
                          "tag-open":"img",
                          "tag-close":"img",
                          "content":"",
                          "align":ui.TextField(),
                          "alt":ui.TextField(),
                          "border":ui.TextField(),
                          "crossorigin":ui.TextField(),
                          "height":ui.TextField(),
                          "hspace":ui.TextField(),
                          "ismap":ui.TextField(),
                          "longdesc":ui.TextField(),
                          "src":ui.TextField(),
                          "usemap":ui.TextField(),
                          "vspace":ui.TextField(),
                          "width":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"input",
         "options": dict({
                          "tag-open":"input",
                          "accept":ui.TextField(),
                          "align":ui.TextField(),
                          "alt":ui.TextField(),
                          "autocomplete":ui.TextField(),
                          "autofocus":ui.TextField(),
                          "checked":ui.TextField(),
                          "disabled":ui.TextField(),
                          "form":ui.TextField(),
                          "formaction":ui.TextField(),
                          "formmethod":ui.TextField(),
                          "formnovalidate":ui.TextField(),
                          "formtarget":ui.TextField(),
                          "height":ui.TextField(),
                          "list":ui.TextField(),
                          "max":ui.TextField(),
                          "maxlength":ui.TextField(),
                          "min":ui.TextField(),
                          "multiple":ui.TextField(),
                          "pattern":ui.TextField(),
                          "placeholder":ui.TextField(),
                          "readonly":ui.TextField(),
                          "required":ui.TextField(),
                          "size":ui.TextField(),
                          "src":ui.TextField(),
                          "step":ui.TextField(),
                          "type":ui.TextField(),
                          "value":ui.TextField(),
                          "width":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"insert - (ins)",
         "options": dict({
                          "tag-open":"ins",
                          "tag-close":"ins",
                          "content":ui.TextField(),
                          "cite":ui.TextField(),
                          "datetime":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"keyboard (kbd)",
         "options": dict({
                          "tag-open":"kbd",
                          "tag-close":"kbd",
                          "content":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"keygen",
         "options": dict({
                          "tag-open":"keygen",
                          "autofocus":ui.TextField(),
                          "challenge":ui.TextField(),
                          "disabled":ui.TextField(),
                          "form":ui.TextField(),
                          "keytype":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"label",
         "options": dict({
                          "tag-open":"label",
                          "tag-close":"label",
                          "content":ui.TextField(),
                          "for":ui.TextField(),
                          "form":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"legend",
         "options": dict({
                          "tag-open":"legend",
                          "tag-close":"legend",
                          "content":ui.TextField(),
                          "align":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"list item (li)",
         "options": dict({
                          "tag-open":"li",
                          "tag-close":"li",
                          "content":ui.TextField(),
                          "type":ui.TextField(),
                          "value":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"link",
         "options": dict({
                     "tag-open":"link",
                     "charset":ui.TextField(),
                     "crossorigin":ui.TextField(),
                     "href":ui.TextField(),
                     "hreflang":ui.TextField(),
                     "media":ui.TextField(),
                     "rel":ui.TextField(),
                     "rev":ui.TextField(),
                     "sizes":ui.TextField(),
                     "target":ui.TextField(),
                     "type":ui.TextField(),
                     }, **GLOBAL_HTML_ATTR)},
        {"title":"main",
         "options": dict({
                          "tag-open":"main",
                          "tag-close":"main",
                          "content":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"map",
         "options": dict({
                          "tag-open":"map",
                          "tag-close":"map",
                          "content":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"mark",
         "options": dict({
                          "tag-open":"mark",
                          "tag-close":"mark",
                          "content":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"menu",
         "options": dict({
                          "tag-open":"menu",
                          "tag-close":"menu",
                          "content":ui.TextField(),
                          "label":ui.TextField(),
                          "type":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"menuitem",
         "options": dict({
                          "tag-open":"menuitem",
                          "tag-close":"menuitem",
                          "content":ui.TextField(),
                          "checked":ui.TextField(),
                          "command":ui.TextField(),
                          "default":ui.TextField(),
                          "disable":ui.TextField(),
                          "icon":ui.TextField(),
                          "label":ui.TextField(),
                          "radiogroup":ui.TextField(),
                          "type":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"metadata",
         "options": dict({
                          "tag-open":"meta",
                          "tag-close":"meta",
                          "content":ui.TextField(),
                          "charset":ui.TextField(),
                          "http-equiv":ui.TextField(),
                          "scheme":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"meter",
         "options": dict({
                          "tag-open":"meter",
                          "tag-close":"meter",
                          "content":ui.TextField(),
                          "form":ui.TextField(),
                          "high":ui.TextField(),
                          "low":ui.TextField(),
                          "max":ui.TextField(),
                          "min":ui.TextField(),
                          "optimum":ui.TextField(),
                          "value":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"navigation block - (nav)",
         "options": dict({
                          "tag-open":"nav",
                          "tag-close":"nav",
                          "content":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"noframes - (Not Avaliable in HTML5)",
         "options": dict({
                          "tag-open":"noframes",
                          "tag-close":"noframes",
                          "content":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"noscript",
         "options": dict({
                          "tag-open":"noscript",
                          "tag-close":"noscript",
                          "content":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"object",
         "options": dict({
                          "tag-open":"object",
                          "tag-close":"object",
                          "content":ui.TextField(),
                          "align":ui.TextField(),
                          "archive":ui.TextField(),
                          "border":ui.TextField(),
                          "classid":ui.TextField(),
                          "codebase":ui.TextField(),
                          "codetype":ui.TextField(),
                          "data":ui.TextField(),
                          "declare":ui.TextField(),
                          "form":ui.TextField(),
                          "height":ui.TextField(),
                          "hspace":ui.TextField(),
                          "standby":ui.TextField(),
                          "type":ui.TextField(),
                          "usemap":ui.TextField(),
                          "vspace":ui.TextField(),
                          "width":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"ordered list (ol)",
         "options": dict({
                          "tag-open":"ol",
                          "tag-close":"ol",
                          "content":ui.TextField(),
                          "compact":ui.TextField(),
                          "reversed":ui.TextField(),
                          "start":ui.TextField(),
                          "type":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"option group (optgroup)",
         "options": dict({
                          "tag-open":"optgroup",
                          "tag-close":"optgroup",
                          "content":ui.TextView(),
                          "disabled":ui.TextField(),
                          "label":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"option",
         "options": dict({
                          "tag-open":"option",
                          "tag-close":"option",
                          "content":ui.TextField(),
                          "disabled":ui.TextField(),
                          "label":ui.TextField(),
                          "selected":ui.TextField(),
                          "value":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"output",
         "options": dict({
                          "tag-open":"output",
                          "tag-close":"output",
                          "content":ui.TextField(),
                          "for":ui.TextField(),
                          "form":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"paragraph",
         "options": dict({
                     "tag-open":"p",
                     "tag-close":"p",
                     "content":ui.TextView(),
                     "align":ui.TextField(),
                     }, **GLOBAL_HTML_ATTR)},
        {"title":"parameter (param)",
         "options": dict({
                          "tag-open":"param",
                          "type":ui.TextField(),
                          "value":ui.TextField(),
                          "valuetype":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"preformatted text",
         "options": dict({
                          "tag-open":"pre",
                          "tag-close":"pre",
                          "content":ui.TextView(),
                          "width":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"progress",
         "options": dict({
                          "tag-open":"progress",
                          "tag-close":"progress",
                          "content":ui.TextField(),
                          "max":ui.TextField(),
                          "value":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"quotation (q)",
         "options": dict({
                          "tag-open":"q",
                          "tag-close":"q",
                          "content":ui.TextField(),
                          "cite":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"rp",
         "options": dict({
                          "tag-open":"rp",
                          "tag-close":"rp",
                          "content":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"rt",
         "options": dict({
                          "tag-open":"rt",
                          "tag-close":"rt",
                          "content":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"ruby",
         "options": dict({
                          "tag-open":"ruby",
                          "tag-close":"ruby",
                          "content":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"s",
         "options": dict({
                          "tag-open":"s",
                          "tag-close":"s",
                          "content":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"samp",
         "options": dict({
                          "tag-open":"samp",
                          "tag-close":"samp",
                          "content":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title": "script",
         "options": dict({
                     "tag-open":"script",
                     "tag-close":"script",
                     "content":ui.TextView(),
                     "async":ui.TextField(),
                     "charset":ui.TextField(),
                     "defer":ui.TextField(),
                     "src": ui.TextField(),
                     "type": ui.TextField(),
                     "xml:space":ui.TextField(),
                     }, **GLOBAL_HTML_ATTR)},
        {"title":"section",
         "options": dict({
                          "tag-open":"section",
                          "tag-close":"section",
                          "content":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"select",
         "options": dict({
                          "tag-open":"select",
                          "tag-close":"select",
                          "content":ui.TextField(),
                          "autofocus":ui.TextField(),
                          "disabled":ui.TextField(),
                          "form":ui.TextField(),
                          "multiple":ui.TextField(),
                          "required":ui.TextField(),
                          "size":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"small",
         "options": dict({
                          "tag-open":"small",
                          "tag-close":"small",
                          "content":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"source",
         "options": dict({
                          "tag-open":"source",
                          "tag-close":"source",
                          "content":ui.TextField(),
                          "media":ui.TextField(),
                          "src":ui.TextField(),
                          "type":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"span",
         "options": dict({
                          "tag-open":"span",
                          "tag-close":"span",
                          "content":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"strike - (Not Avaliable in HTML5)",
         "options": dict({
                          "tag-open":"strike",
                          "tag-close":"strike",
                          "content":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"strong",
         "options": dict({
                          "tag-open":"strong",
                          "tag-close":"strong",
                          "content":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title": "style",
         "options": dict({
                     "tag-open":"style",
                     "tag-close":"style",
                     "content":ui.TextView(),
                     "media":ui.TextField(),
                     "scoped":ui.TextField(),
                     "type":ui.TextField(),
                     }, **GLOBAL_HTML_ATTR)},
        {"title":"subscript - (sub)",
         "options": dict({
                          "tag-open":"sub",
                          "tag-close":"sub",
                          "content":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"summary",
         "options": dict({
                          "tag-open":"summary",
                          "tag-close":"summary",
                          "content":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"superscript - (sup)",
         "options": dict({
                          "tag-open":"sup",
                          "tag-close":"sup",
                          "content":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"table",
         "options": dict({
                          "tag-open":"table",
                          "tag-close":"table",
                          "content":ui.TextField(),
                          "align":ui.TextField(),
                          "bgcolor":ui.TextField(),
                          "border":ui.TextField(),
                          "cellpadding":ui.TextField(),
                          "cellspacing":ui.TextField(),
                          "frame":ui.TextField(),
                          "sortable":ui.TextField(),
                          "summary":ui.TextField(),
                          "width":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"table body (tbody)",
         "options": dict({
                          "tag-open":"tbody",
                          "tag-close":"tbody",
                          "content":ui.TextField(),
                          "align":ui.TextField(),
                          "char":ui.TextField(),
                          "charoff":ui.TextField(),
                          "valign":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"tablecell (td)",
         "options": dict({
                          "tag-open":"td",
                          "tag-close":"td",
                          "content":ui.TextField(),
                          "abbr":ui.TextField(),
                          "align":ui.TextField(),
                          "axis":ui.TextField(),
                          "bgcolor":ui.TextField(),
                          "char":ui.TextField(),
                          "charoff":ui.TextField(),
                          "colspan":ui.TextField(),
                          "headers":ui.TextField(),
                          "height":ui.TextField(),
                          "nowrap":ui.TextField(),
                          "rowspan":ui.TextField(),
                          "scope":ui.TextField(),
                          "valign":ui.TextField(),
                          "width":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"textarea",
         "options": dict({
                          "tag-open":"textarea",
                          "tag-close":"textarea",
                          "content":ui.TextField(),
                          "autofocus":ui.TextField(),
                          "cols":ui.TextField(),
                          "disabled":ui.TextField(),
                          "form":ui.TextField(),
                          "maxlength":ui.TextField(),
                          "placeholder":ui.TextField(),
                          "readonly":ui.TextField(),
                          "required":ui.TextField(),
                          "rows":ui.TextField(),
                          "wrap":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"table footer (tfoot)",
         "options": dict({
                          "tag-open":"tfoot",
                          "tag-close":"tfoot",
                          "content":ui.TextField(),
                          "align":ui.TextField(),
                          "char":ui.TextField(),
                          "charoff":ui.TextField(),
                          "valign":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"table header cell (th)",
         "options": dict({
                          "tag-open":"th",
                          "tag-close":"th",
                          "content":ui.TextField(),
                          "abbr":ui.TextField(),
                          "align":ui.TextField(),
                          "axis":ui.TextField(),
                          "bgcolor":ui.TextField(),
                          "char":ui.TextField(),
                          "charoff":ui.TextField(),
                          "colspan":ui.TextField(),
                          "headers":ui.TextField(),
                          "height":ui.TextField(),
                          "nowrap":ui.TextField(),
                          "rowspan":ui.TextField(),
                          "scope":ui.TextField(),
                          "sorted":ui.TextField(),
                          "valign":ui.TextField(),
                          "width":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"table header (thead)",
         "options": dict({
                          "tag-open":"thead",
                          "tag-close":"thead",
                          "content":ui.TextField(),
                          "align":ui.TextField(),
                          "char":ui.TextField(),
                          "charoff":ui.TextField(),
                          "valign":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
        {"title":"time",
         "options": dict({
                          "tag-open":"time",
                          "tag-close":"time",
                          "content":ui.TextField(),
                          "datetime":ui.TextField(),
                          }, **GLOBAL_HTML_ATTR)},
         {"title":"title",
          "options": dict({
                           "tag-open":"title",
                           "tag-close":"title",
                           "content":ui.TextField(),
                           }, **GLOBAL_HTML_ATTR)},
         {"title":"table row (tr)",
          "options": dict({
                           "tag-open":"tr",
                           "tag-close":"tr",
                           "content":ui.TextField(),
                           "align":ui.TextField(),
                           "bgcolor":ui.TextField(),
                           "char":ui.TextField(),
                           "charoff":ui.TextField(),
                           "valign":ui.TextField(),
                           }, **GLOBAL_HTML_ATTR)},
         {"title":"track",
          "options": dict({
                           "tag-open":"track",
                           "default":ui.TextField(),
                           "kind":ui.TextField(),
                           "label":ui.TextField(),
                           "src":ui.TextField(),
                           "srclang":ui.TextField(),
                           }, **GLOBAL_HTML_ATTR)},
         {"title":"teletype text (tt) - (Not Avaliable in HTML5)",
          "options": dict({
                           "tag-open":"tt",
                           "tag-close":"tt",
                           "content":ui.TextField(),
                           }, **GLOBAL_HTML_ATTR)},
         {"title":"underline (u)",
          "options": dict({
                           "tag-open":"u",
                           "tag-close":"u",
                           "content":ui.TextField(),
                           }, **GLOBAL_HTML_ATTR)},
         {"title":"unordered list (ul)",
          "options": dict({
                           "tag-open":"ul",
                           "tag-close":"ul",
                           "content":ui.TextField(),
                           "compact":ui.TextField(),
                           "type":ui.TextField(),
                           }, **GLOBAL_HTML_ATTR)},
         {"title":"variable (var)",
          "options": dict({
                           "tag-open":"var",
                           "tag-close":"var",
                           "content":ui.TextField(),
                           }, **GLOBAL_HTML_ATTR)},
         {"title":"video",
          "options": dict({
                           "tag-open":"video",
                           "tag-close":"video",
                           "content":ui.TextField(),
                           "autoplay":ui.TextField(),
                           "controls":ui.TextField(),
                           "height":ui.TextField(),
                           "loop":ui.TextField(),
                           "muted":ui.TextField(),
                           "poster":ui.TextField(),
                           "preload":ui.TextField(),
                           "src":ui.TextField(),
                           "width":ui.TextField(),
                           }, **GLOBAL_HTML_ATTR)},
         {"title":"word break opportunity (wbr)",
          "options": dict({
                           "tag-open":"wbr",
                           "tag-close":"wbr",
                           "content":ui.TextField(),
                           }, **GLOBAL_HTML_ATTR)},
         {"title": "comment",
          "options": {
                      "tag-open":"<!--",
                      "tag-close":"-->",
                      "content":ui.TextView(),
                      }},
]

print "%i GLOBAL_HTML_ATTR" % len(GLOBAL_HTML_ATTR)
print "%i ALL_EVENTS" % len(ALL_EVENTS)
print "%i TAGS" % len(TAGS)
print "%i TOTAL" % (len(GLOBAL_HTML_ATTR) + len(ALL_EVENTS) + len(TAGS))
